# Generated by Django 5.0.2 on 2024-02-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='file_upload',
            field=models.ImageField(blank=True, null=True, upload_to='file_upload/'),
        ),
    ]
