# Generated by Django 5.0.2 on 2024-02-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0004_alter_userprofile_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file_upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
