# Generated by Django 5.0.2 on 2024-02-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0008_contactusmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUsMessage',
        ),
    ]
