# Generated by Django 5.0.2 on 2024-02-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPMS', '0009_delete_contactusmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=True, max_length=254, unique=True),
        ),
    ]
